### ISSUE TITLE
Tom_Nonlocalizedevents is out of date with Tom_base

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_nonlocalizedevents#37]
### Immediate Tasks:
- [x] #46 
  - tom_nonlocalizedevents 0.9.0 released. ✔️  
- [ ] #64 
- [ ] #62 
- [ ] #41 

### Tasks
- [ ] #63 
- [ ] Expand related messages shown to include gcn circulars that reference NLE 
- [ ] Add button to submit event candidate targets to HERMES with a message 
- [ ] #40 

### Additional Tasks:
 - [ ] integrating treasure map into page
 - [ ] integrating Alladin map of NLE into page (see also #62)
 - [ ] expanding related event messages to see full text doesn't work - only shows message title :beetle:
 - [ ] related event messages only shows counterpart notices and hermes messages - should also show gcn circulars that reference NLE :beetle:

### Completed Tasks
- [x] Possible issue with migrations across BaseTarget name change. 
- [x] Update dependencies of project 
- [x] Expand creating event candidates from LVC_COUNTERPART messages
- [x] Fix related messages shown to show full message text, not just title 🐞 
- [x] Add Navbar integration point
- [x] #61 
- [x] Tests are failing for dependabot PRs.
- [x] `django-filter` has incompatible requirements with tom_base.
- [x] `ligo-skymap` fails on a python 3.8 installation with the following error:
```
Incompatible constraints in requirements of oldest-supported-numpy (2022.11.19):
  numpy (==1.22.2) ; platform_machine == "loongarch64" and python_version < "3.11" or python_version == "3.8" and platform_python_implementation == "PyPy"
  numpy (==1.21.0) ; python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"
```

# Here are the transcribed notes from LCOGT/sprint-planning#98

**Effort:** 2
**Created:** Oct 14, 2024
### Description:
As a tom user, I would like the tom_nonlocalizedevents plugin to be up to date. It hasn't really been developed for over a year, so it is in need of some TLC and updating of libraries as well as some updates for tighter HERMES integration.

Some  bugs or broken things:
* expanding related event messages to see full text doesn't work - only shows message title
* related event messages only shows counterpart notices and hermes messages - should also show gcn circulars that reference NLE

Tighter HERMES integration:
* Add button to submit NLE target candidates to HERMES with a message

**Labels:** hermes, scimma, scimma-team, tom toolkit

**Comment by jchate6** [comment]
Re-activating because TOM_NonlocalizedEvents still needs to be updated.

**Comment by jchate6** [comment]
Check with respect to:
 -  TOMToolkit/tom_base#1055

**Comment by rachel3834** [comment]
Related:
- [ ] SAGUARO-MMA/saguaro_tom#132
