### ISSUE TITLE
Add Icecube support to `tom_nonlocalizedevents`

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_nonlocalizedevents#40]
As a TOM user, I would like to be able to ingest ICECUBE skymaps and events from ICECUBE_[CASCADE|BRONZE|GOLD] notices. I would like to use the tom_nonlocalizedevents interface to view these events, and see related info about them and their skymap and targets within their skymap. To facilitate this, we need to make some modifications to the tom_nonlocalizedevents infrastructure and UI to support icecube events since they have different properties from GW events.

CASCADE events have a skymap, while BRONZE/GOLD events just have a source and maybe error associated. All are considered nonlocalizedevents though so they should be read into the system as such, just some won't have a skymap so perhaps the credible region calc will vary since they instead have a 90/50% credible region as an error radius

#### Tasks:

- [ ] refactor nonlocalizedevent model as necessary for icecube support
- [ ] Write ingestor for ICECUBE_* gcn events 
- [ ] Create NLE detail page that is analog to GravitationalWaveBanner but for properties of Icecube alerts
- [ ] Modify credible region calculation for icecube BRONZE/GOLD events which have a 50/90 cr error radius
- [ ] Refactor Superevent vue pages to not specifically refer to gracedb images unless they are GW event - see if there are icecube analogs to those images.
- [ ] Bonus: create those images ourselves for icecube using the event localization
- [ ] test and deploy

**Comment by dsand** [comment]
Hey Everyone -- I'm checking in on this IceCube issue.  This would be very very useful for the SAGUARO TOM.  @griffin-h and others on our team are starting to work on this.  Can we collaborate to make this happen?

**Comment by rachel3834** [comment]
Hi @dsand @griffin-h Yes, absolutely.  In fact we already had a plan to update this module in the next sprint which starts in just over a week.  It would be great to talk with you about the best direction to take this.  I'll reach out by email.
